export type Category = "whatsapp" | "crm" | "atendimento" | "ia" | "vendas" | "organizacao";

export type Post = {
  title: string;
  description: string;
  href: string;
  category: Category;
  categoryLabel: string;
  readTime: string;
  featured?: boolean;
  publishedAt?: string;
};

export const CATEGORIES: Record<Category, string> = {
  whatsapp: "WhatsApp",
  crm: "CRM",
  atendimento: "Atendimento",
  ia: "IA",
  vendas: "Vendas",
  organizacao: "Organização",
};

export const posts: Post[] = [
  // WhatsApp
  {
    title: "Como reduzir o tempo de resposta no WhatsApp da empresa",
    description: "Guia prático para responder mais rápido no WhatsApp sem perder qualidade.",
    href: "/blog/como-reduzir-o-tempo-de-resposta-no-whatsapp-da-empresa",
    category: "whatsapp",
    categoryLabel: "WhatsApp",
    readTime: "7 min",
    featured: true,
  },
  {
    title: "Como usar respostas rápidas sem deixar o atendimento robótico",
    description: "Guia prático para usar respostas rápidas com contexto e atendimento humano.",
    href: "/blog/como-usar-respostas-rapidas-sem-deixar-o-atendimento-robotico",
    category: "whatsapp",
    categoryLabel: "WhatsApp",
    readTime: "7 min",
  },
  {
    title: "Respostas rápidas no WhatsApp: como padronizar o atendimento",
    description: "Como usar respostas rápidas no WhatsApp para padronizar o atendimento comercial e reduzir tempo de resposta.",
    href: "/blog/respostas-rapidas-no-whatsapp-como-padronizar-o-atendimento-comercial",
    category: "whatsapp",
    categoryLabel: "WhatsApp",
    readTime: "7 min",
  },
  {
    title: "Como responder clientes mais rápido no WhatsApp sem perder qualidade",
    description: "Como responder mais rápido usando respostas rápidas, CRM, organização, equipe e IA.",
    href: "/blog/como-responder-clientes-mais-rapido-no-whatsapp-sem-perder-qualidade",
    category: "whatsapp",
    categoryLabel: "WhatsApp",
    readTime: "7 min",
  },
  {
    title: "Atendimento multiatendente no WhatsApp: quando usar",
    description: "Quando sua empresa precisa de atendimento multiatendente e como organizar responsáveis, histórico e equipe.",
    href: "/blog/atendimento-multiatendente-no-whatsapp-quando-sua-empresa-precisa-disso",
    category: "whatsapp",
    categoryLabel: "WhatsApp",
    readTime: "7 min",
  },
  // CRM
  {
    title: "CRM com WhatsApp: como funciona na prática",
    description: "Como um CRM com WhatsApp ajuda a organizar conversas, clientes, oportunidades e funil de vendas.",
    href: "/blog/crm-com-whatsapp-como-funciona-na-pratica",
    category: "crm",
    categoryLabel: "CRM",
    readTime: "7 min",
    featured: true,
  },
  {
    title: "CRM para equipe comercial: como organizar vendedores e atendentes",
    description: "Como organizar equipe comercial, responsáveis, etapas e oportunidades com CRM.",
    href: "/blog/crm-para-equipe-comercial-como-organizar-vendedores-e-atendentes",
    category: "crm",
    categoryLabel: "CRM",
    readTime: "7 min",
  },
  {
    title: "CRM para WhatsApp: como organizar vendas e atendimento em um só lugar",
    description: "Como um CRM para WhatsApp ajuda pequenas empresas a organizar atendimento, vendas e clientes.",
    href: "/blog/crm-para-whatsapp-como-organizar-vendas-e-atendimento-em-um-so-lugar",
    category: "crm",
    categoryLabel: "CRM",
    readTime: "7 min",
  },
  {
    title: "Melhor CRM para pequenas empresas: como escolher sem complicar",
    description: "Como escolher o melhor CRM considerando simplicidade, WhatsApp, funil de vendas e controle comercial.",
    href: "/blog/melhor-crm-para-pequenas-empresas-como-escolher-sem-complicar",
    category: "crm",
    categoryLabel: "CRM",
    readTime: "7 min",
  },
  // Atendimento
  {
    title: "Atendimento comercial pelo WhatsApp: como criar um processo simples",
    description: "Como criar um processo comercial simples para atendimento pelo WhatsApp.",
    href: "/blog/atendimento-comercial-pelo-whatsapp-como-criar-um-processo-simples",
    category: "atendimento",
    categoryLabel: "Atendimento",
    readTime: "7 min",
    featured: true,
  },
  {
    title: "Como organizar o histórico de clientes no WhatsApp",
    description: "Como organizar histórico de clientes, conversas e contexto no atendimento.",
    href: "/blog/como-organizar-o-historico-de-clientes-no-whatsapp",
    category: "atendimento",
    categoryLabel: "Atendimento",
    readTime: "7 min",
  },
  {
    title: "Como controlar atendentes no WhatsApp sem perder qualidade",
    description: "Como controlar atendentes com responsáveis, histórico, indicadores e CRM.",
    href: "/blog/como-controlar-atendentes-no-whatsapp-sem-perder-qualidade",
    category: "atendimento",
    categoryLabel: "Atendimento",
    readTime: "7 min",
  },
  {
    title: "Indicadores de atendimento no WhatsApp: o que o gestor precisa acompanhar",
    description: "Quais indicadores acompanhar para melhorar atendimento e vendas pelo WhatsApp.",
    href: "/blog/indicadores-de-atendimento-no-whatsapp-o-que-o-gestor-precisa-acompanhar",
    category: "atendimento",
    categoryLabel: "Atendimento",
    readTime: "7 min",
  },
  // IA
  {
    title: "IA no atendimento pelo WhatsApp: como usar sem perder o toque humano",
    description: "Como usar IA para apoiar o atendimento comercial sem abrir mão da supervisão humana.",
    href: "/blog/ia-no-atendimento-pelo-whatsapp-como-usar-sem-perder-o-toque-humano",
    category: "ia",
    categoryLabel: "IA",
    readTime: "7 min",
    featured: true,
  },
  {
    title: "Transcrição de áudio no WhatsApp: por que isso ajuda no atendimento",
    description: "Como a transcrição de áudio aumenta produtividade e organização no atendimento.",
    href: "/blog/transcricao-de-audio-no-whatsapp-ajuda-no-atendimento",
    category: "ia",
    categoryLabel: "IA",
    readTime: "7 min",
  },
  // Vendas
  {
    title: "Funil de vendas no WhatsApp: como acompanhar cada cliente",
    description: "Como usar um funil de vendas para acompanhar clientes, orçamentos, follow-ups e fechamentos.",
    href: "/blog/funil-de-vendas-no-whatsapp-como-acompanhar-cada-cliente",
    category: "vendas",
    categoryLabel: "Vendas",
    readTime: "7 min",
    featured: true,
  },
  {
    title: "Como não perder vendas que chegam pelo WhatsApp",
    description: "Como evitar perdas comerciais com organização, CRM, follow-up e acompanhamento da equipe.",
    href: "/blog/como-nao-perder-vendas-que-chegam-pelo-whatsapp",
    category: "vendas",
    categoryLabel: "Vendas",
    readTime: "7 min",
  },
  {
    title: "Como saber se sua equipe está perdendo vendas no WhatsApp",
    description: "Como identificar perdas comerciais no atendimento pelo WhatsApp.",
    href: "/blog/como-saber-se-sua-equipe-esta-perdendo-vendas-no-whatsapp",
    category: "vendas",
    categoryLabel: "Vendas",
    readTime: "7 min",
  },
  {
    title: "Como transformar conversas do WhatsApp em oportunidades de venda",
    description: "Como transformar conversas em oportunidades com qualificação, CRM, funil e histórico.",
    href: "/blog/como-transformar-conversas-do-whatsapp-em-oportunidades-de-venda",
    category: "vendas",
    categoryLabel: "Vendas",
    readTime: "7 min",
  },
  {
    title: "Como acompanhar orçamentos enviados pelo WhatsApp",
    description: "Como acompanhar orçamentos com follow-up, etapas comerciais, CRM e histórico.",
    href: "/blog/como-acompanhar-orcamentos-enviados-pelo-whatsapp",
    category: "vendas",
    categoryLabel: "Vendas",
    readTime: "7 min",
  },
  {
    title: "Como organizar clientes no WhatsApp sem perder vendas",
    description: "Como organizar clientes, controlar orçamentos, follow-ups e evitar perdas comerciais.",
    href: "/blog/como-organizar-clientes-no-whatsapp-sem-perder-vendas",
    category: "vendas",
    categoryLabel: "Vendas",
    readTime: "7 min",
  },
  // New articles (2025-06)
  // Atendimento
  {
    title: "Como criar um SLA de atendimento no WhatsApp",
    description: "Como definir e monitorar tempo máximo de resposta no WhatsApp para garantir qualidade no atendimento.",
    href: "/blog/como-criar-sla-de-atendimento-no-whatsapp",
    category: "atendimento",
    categoryLabel: "Atendimento",
    readTime: "6 min",
    publishedAt: "2026-06-19",
  },
  {
    title: "Como montar uma equipe de atendimento no WhatsApp do zero",
    description: "Como estruturar funções, processos e ferramentas para um time de atendimento que funciona no WhatsApp.",
    href: "/blog/como-montar-equipe-de-atendimento-no-whatsapp-do-zero",
    category: "atendimento",
    categoryLabel: "Atendimento",
    readTime: "8 min",
    publishedAt: "2026-06-19",
  },
  {
    title: "Como passar um cliente para outro atendente no WhatsApp sem perder contexto",
    description: "Como fazer transições de atendimento suaves com histórico e contexto preservados.",
    href: "/blog/como-passar-cliente-para-outro-atendente-no-whatsapp-sem-perder-contexto",
    category: "atendimento",
    categoryLabel: "Atendimento",
    readTime: "6 min",
    publishedAt: "2026-06-19",
  },
  {
    title: "Como padronizar o atendimento de uma equipe no WhatsApp",
    description: "Como criar um processo que todos sigam sem perder a naturalidade no atendimento pelo WhatsApp.",
    href: "/blog/como-padronizar-atendimento-de-equipe-no-whatsapp",
    category: "atendimento",
    categoryLabel: "Atendimento",
    readTime: "7 min",
    publishedAt: "2026-06-19",
  },
  {
    title: "Como medir o desempenho da equipe de atendimento pelo WhatsApp",
    description: "Quais indicadores acompanhar para identificar problemas antes que cheguem ao cliente.",
    href: "/blog/como-medir-desempenho-da-equipe-de-atendimento-pelo-whatsapp",
    category: "atendimento",
    categoryLabel: "Atendimento",
    readTime: "7 min",
    publishedAt: "2026-06-19",
  },
  // Vendas
  {
    title: "Como recuperar clientes que pararam de responder no WhatsApp",
    description: "Estratégias práticas para reativar contatos que sumiram sem forçar a barra.",
    href: "/blog/como-recuperar-clientes-que-pararam-de-responder-no-whatsapp",
    category: "vendas",
    categoryLabel: "Vendas",
    readTime: "7 min",
    publishedAt: "2026-06-19",
  },
  {
    title: "Como fazer follow-up sem ser chato no WhatsApp",
    description: "Como retomar contatos com clientes no momento certo e com a mensagem certa.",
    href: "/blog/como-fazer-follow-up-sem-ser-chato-no-whatsapp",
    category: "vendas",
    categoryLabel: "Vendas",
    readTime: "7 min",
    publishedAt: "2026-06-19",
  },
  {
    title: "Por que seu time perde vendas no WhatsApp sem perceber",
    description: "Os padrões de perda mais comuns no WhatsApp e como corrigir antes que virem hábito.",
    href: "/blog/por-que-seu-time-perde-vendas-no-whatsapp-sem-perceber",
    category: "vendas",
    categoryLabel: "Vendas",
    readTime: "7 min",
    publishedAt: "2026-06-19",
  },
  {
    title: "Como usar o WhatsApp para vender sem parecer vendedor",
    description: "Como criar conversas que avançam naturalmente para o fechamento sem pressão.",
    href: "/blog/como-usar-whatsapp-para-vender-sem-parecer-vendedor",
    category: "vendas",
    categoryLabel: "Vendas",
    readTime: "7 min",
    publishedAt: "2026-06-19",
  },
  {
    title: "Como organizar o pós-venda pelo WhatsApp",
    description: "Como criar um processo que transforma compradores em clientes recorrentes.",
    href: "/blog/como-organizar-pos-venda-pelo-whatsapp",
    category: "vendas",
    categoryLabel: "Vendas",
    readTime: "7 min",
    publishedAt: "2026-06-19",
  },
  {
    title: "Como crescer as vendas pelo WhatsApp sem aumentar a equipe",
    description: "Com processo e ferramenta certos, a mesma equipe pode atender mais e converter melhor.",
    href: "/blog/como-crescer-vendas-pelo-whatsapp-sem-aumentar-a-equipe",
    category: "vendas",
    categoryLabel: "Vendas",
    readTime: "8 min",
    publishedAt: "2026-06-19",
  },
  // CRM
  {
    title: "O que é CRM Kanban e como funciona para quem vende pelo WhatsApp",
    description: "CRM Kanban organiza oportunidades em colunas visuais para equipes que atendem pelo WhatsApp.",
    href: "/blog/o-que-e-crm-kanban-e-como-funciona-para-quem-vende-pelo-whatsapp",
    category: "crm",
    categoryLabel: "CRM",
    readTime: "7 min",
    publishedAt: "2026-06-19",
  },
  {
    title: "Como usar etiquetas no CRM para organizar clientes por etapa",
    description: "Como usar etiquetas com consistência para ganhar clareza no pipeline.",
    href: "/blog/como-usar-etiquetas-no-crm-para-organizar-clientes-por-etapa",
    category: "crm",
    categoryLabel: "CRM",
    readTime: "6 min",
    publishedAt: "2026-06-19",
  },
  {
    title: "Como saber quais clientes estão esquecidos no pipeline",
    description: "Como identificar e reativar contatos esquecidos antes que decidam com o concorrente.",
    href: "/blog/como-saber-quais-clientes-estao-esquecidos-no-pipeline",
    category: "crm",
    categoryLabel: "CRM",
    readTime: "6 min",
    publishedAt: "2026-06-19",
  },
  {
    title: "Como usar notas de cliente no CRM para não perder contexto",
    description: "Como registrar contexto que realmente ajuda a equipe a vender e atender melhor.",
    href: "/blog/como-usar-notas-de-cliente-no-crm-para-nao-perder-contexto",
    category: "crm",
    categoryLabel: "CRM",
    readTime: "6 min",
    publishedAt: "2026-06-19",
  },
  // WhatsApp
  {
    title: "Como organizar múltiplos WhatsApp em uma só central",
    description: "Como centralizar múltiplos números em um painel único com histórico e equipes separadas.",
    href: "/blog/como-organizar-multiplos-whatsapp-em-uma-so-central",
    category: "whatsapp",
    categoryLabel: "WhatsApp",
    readTime: "7 min",
    publishedAt: "2026-06-19",
  },
  {
    title: "Como atender clientes de grupos do WhatsApp sem responder automaticamente",
    description: "Como usar grupos com inteligência sem bot e sem misturar atendimento individual.",
    href: "/blog/como-atender-clientes-de-grupos-do-whatsapp-sem-responder-automaticamente",
    category: "whatsapp",
    categoryLabel: "WhatsApp",
    readTime: "7 min",
    publishedAt: "2026-06-19",
  },
  // Organização
  {
    title: "Como registrar o histórico de clientes que vieram pelo WhatsApp",
    description: "Como criar uma rotina para registrar o histórico desde o primeiro contato.",
    href: "/blog/como-registrar-historico-de-clientes-que-vieram-pelo-whatsapp",
    category: "organizacao",
    categoryLabel: "Organização",
    readTime: "6 min",
    publishedAt: "2026-06-19",
  },
  {
    title: "Como evitar que mensagens importantes se percam no WhatsApp",
    description: "Como organizar o atendimento para que nada urgente passe despercebido.",
    href: "/blog/como-evitar-que-mensagens-importantes-se-percam-no-whatsapp",
    category: "organizacao",
    categoryLabel: "Organização",
    readTime: "6 min",
    publishedAt: "2026-06-19",
  },
  {
    title: "Como definir a próxima ação para cada cliente no WhatsApp",
    description: "Como criar o hábito de registrar o que fazer com cada cliente e manter o pipeline avançando.",
    href: "/blog/como-definir-proxima-acao-para-cada-cliente-no-whatsapp",
    category: "organizacao",
    categoryLabel: "Organização",
    readTime: "6 min",
    publishedAt: "2026-06-19",
  },
  // Organização (original)
  {
    title: "Como organizar atendimento, vendas e CRM em uma única operação",
    description: "Como integrar atendimento, vendas, CRM, histórico e IA em uma única operação.",
    href: "/blog/como-organizar-atendimento-vendas-e-crm-em-uma-unica-operacao",
    category: "organizacao",
    categoryLabel: "Organização",
    readTime: "7 min",
    featured: true,
  },
  {
    title: "Como organizar prioridades no atendimento pelo WhatsApp",
    description: "Como priorizar conversas, oportunidades e próximas ações no WhatsApp.",
    href: "/blog/como-organizar-prioridades-no-atendimento-pelo-whatsapp",
    category: "organizacao",
    categoryLabel: "Organização",
    readTime: "7 min",
  },
  {
    title: "Como organizar o follow-up de vendas pelo WhatsApp",
    description: "Como estruturar follow-ups no WhatsApp para não perder oportunidades e fechar mais vendas.",
    href: "/blog/como-organizar-follow-up-de-vendas-pelo-whatsapp",
    category: "organizacao",
    categoryLabel: "Organização",
    readTime: "7 min",
  },
];

export function getPostsByCategory(category?: Category | null): Post[] {
  if (!category) return posts;
  return posts.filter((p) => p.category === category);
}

export function getFeaturedPosts(): Post[] {
  return posts.filter((p) => p.featured);
}
